# https://github.com/gohugoio/hugo/blob/master/docs/config/_default/config.toml
baseURL = "https://stunning-real-estate-basic-template.netlify.com/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en-us"
languageLang = "en"
metaDataFormat = "yaml"
title = "Stunning Real Estate Basic Template"
# googleAnalytics = ""
# pluralizeListTitles = false
# disableAliases = true

# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

enableRobotsTXT = true
buildDrafts = true

[blackfriday]
plainIDAnchors = true
# See https://github.com/gohugoio/hugo/issues/2424
hrefTargetBlank = false
extensions = ["hardLineBreak"]

[author]
name = "Stuart Stephens"
[social]
twitter = "StuartAStephens"

[params]
  description = "Custom Web Design for Modern Businesses"

[menu]
    [[menu.main]]
    identifier = "hero"
    name       = "Hero Scenes"
    url        = "/hero-scenes/"
    weight     = 1

    [[menu.main]]
    identifier = "temp1"
    name       = "temp1"
    url        = "/temp1/"
    weight     = 2

    [[menu.main]]
    identifier = "temp2"
    name       = "temp2"
    url        = "/temp2/"
    weight     = 3